### ISSUE TITLE
Don't require the action `id` attribute

### ISSUE THREAD

**Issue by yoshutch** [byu-oit/github-action-teams#10]
Is there a way to not require the `id` for the GHA? It looks like it is used in the notification to say what "Workflow" succeeded/failed, but could it just lookup the name of the workflow that the action is on and use that? Maybe provide a way to override it if needed (like an attribute `workflow_name`)?

**Comment by GaryGSC** [comment]
Should be resolved in [v3](https://github.com/byu-oit/github-action-teams/releases/tag/v3.0.0).
